name: MeetUp-backend

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Logga in på Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      



      - name: Bygg Docker Image
        run: docker build -t Khaahir/meetup-backend .

      - name: pusch docker Image
        run: docker push Khaahir/meetup-backend
  


      - name: Trigga Render Deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}